"""Phase 4: auto-generate results/poc_summary.md from the computed results.

This keeps the summary reproducible (e.g. on Colab) instead of hand-written.
Critically, it runs a degeneracy check on the trajectories: if the agent never
produced genuine multi-hop reasoning (repetitive steps, 0 success), the
correlation is a test on noise, so the summary reports INCONCLUSIVE rather than
mapping r straight onto a go/no-go band.

Run:  python -m analysis.summarize
"""
from __future__ import annotations

import json

from interp.activation_cache import ANSWER_CUE, LAYER, MODEL_NAME, RESULTS_DIR

TRAJ_PATH = RESULTS_DIR / "trajectories.json"
FAST_PATH = RESULTS_DIR / "fast_scores.json"
SLOW_PATH = RESULTS_DIR / "slow_scores.json"
CORR_PATH = RESULTS_DIR / "correlation.json"
OUT_PATH = RESULTS_DIR / "poc_summary.md"


def _repetition_rate(step_texts: list[str]) -> float:
    """Fraction of steps that duplicate an earlier step in the same trajectory."""
    if len(step_texts) <= 1:
        return 0.0
    seen, dupes = set(), 0
    for t in step_texts:
        key = t.strip().lower()
        if key in seen:
            dupes += 1
        seen.add(key)
    return dupes / len(step_texts)


def main() -> None:
    trajectories = json.loads(TRAJ_PATH.read_text(encoding="utf-8"))
    fast = json.loads(FAST_PATH.read_text(encoding="utf-8"))
    slow = json.loads(SLOW_PATH.read_text(encoding="utf-8"))
    corr = json.loads(CORR_PATH.read_text(encoding="utf-8"))

    n = len(trajectories)
    n_success = sum(t["success"] for t in trajectories)
    single_step = sum(1 for t in trajectories if len(t["step_positions"]) == 1)
    rep_rates = [_repetition_rate(t["step_texts"]) for t in trajectories]
    avg_rep = sum(rep_rates) / n if n else 0.0

    # Degeneracy: lots of repeated steps or nothing solved -> trajectories are
    # not real multi-hop reasoning, so the correlation does not test the method.
    degenerate = (n_success == 0 and avg_rep > 0.3) or single_step > n / 2

    r = corr["pearson_r"]

    # Top |fast| step per trajectory for the qualitative read.
    top_lines = []
    for t in trajectories:
        scores = fast[t["id"]]
        i = max(range(len(scores)), key=lambda k: abs(scores[k]))
        txt = t["step_texts"][i].replace("\n", " ")[:80]
        top_lines.append(
            f"- `{t['id'][:8]}` (gold: {t['gold_answer']!r}, success={t['success']}): "
            f"top step {i + 1}/{len(scores)} fast={scores[i]:+.3f} "
            f"slow={slow[t['id']][i]:+.3f} -- {txt!r}"
        )

    if degenerate:
        verdict = "INCONCLUSIVE (degenerate trajectories)"
        recommendation = (
            "The agent did not produce genuine multi-hop reasoning "
            f"(success {n_success}/{n}, avg within-trajectory step-repetition "
            f"{avg_rep:.0%}, {single_step}/{n} single-step). The fast-vs-slow "
            "correlation was therefore measured on near-degenerate text, so it "
            "neither validates nor refutes the method. **Do not treat r as a "
            "go/no-go.** Re-run with a model/loop that yields distinguishable "
            "reasoning steps before drawing a conclusion."
        )
    else:
        verdict = corr["band"].upper()
        recommendation = corr["action"]

    md = f"""# Veritas PoC - Results Summary

_Auto-generated by `analysis/summarize.py` from the computed results._

## The number (go/no-go metric)

| Metric | Value |
|---|---|
| Model | `{MODEL_NAME}` |
| Pearson r (fast vs. slow) | **{r:.3f}** |
| p-value | {corr['p_value']:.4f} |
| Steps compared | {corr['n_steps']} (across {n} trajectories) |
| Layer patched | {LAYER} |
| Verdict | **{verdict}** |

## Trajectory health check

- Success: {n_success}/{n}
- Single-step trajectories: {single_step}/{n}
- Avg within-trajectory step repetition: {avg_rep:.0%}
- Degenerate (correlation untrustworthy): **{degenerate}**

## The answer-token decision (flagged explicitly, per PROPOSAL.md)

The single scalar both methods perturb is the **logit of the first token of the
gold answer**, read at the final position of one forward pass over
`<trajectory text> + "{ANSWER_CUE.strip()}"`. Both attribution patching (fast)
and activation patching (slow) measure their effect on this exact number.

## Top-scored step per trajectory (qualitative read)

{chr(10).join(top_lines)}

## Standing methodological caveats

1. **Zero-ablation counterfactual.** Attribution patching is a first-order
   (linear) approximation; zeroing a whole residual is a large, off-distribution
   perturbation, the regime where the linear approximation is weakest. Some
   fast/slow disagreement is expected from this choice alone.
2. **Single layer, single counterfactual, 5-10 trajectories** - this is a
   direction-validation PoC, not a publication-grade measurement.

## Recommendation

{recommendation}

## Reproduce

```bash
python -m agent.runner
python -m interp.attribution_patch
python -m interp.ground_truth_patch
python -m analysis.correlate
python -m analysis.visualize
python -m analysis.summarize
```
"""
    OUT_PATH.write_text(md, encoding="utf-8")
    print(f"Wrote {OUT_PATH}")
    print(f"Verdict: {verdict}  (degenerate={degenerate}, r={r:.3f})")


if __name__ == "__main__":
    main()
